### ISSUE TITLE
Failed to put a frame with status code 0x3200000d

### ISSUE THREAD

**Issue by tongvantruong** [awsdocs/AWS-Kinesis-Video-Documentation#10]
Related issue: https://github.com/aws-amplify/aws-sdk-android/issues/909

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
