### ISSUE TITLE
PutMediaDemo don´t display video at console

### ISSUE THREAD

**Issue by daxart** [awsdocs/AWS-Kinesis-Video-Documentation#13]
I have run the demo several times and although in the logs it says that it is transmitting in the console I can not see video, the message is: "No fragments were found, check that the medium is being transmitted and that the timestamps of the fragment are correct . "
onAckEvent AckEvent{ackEventType=PERSISTED, fragmentTimecode=7998, fragmentNumber='91343852333182799098292474309786995924447542126', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=RECEIVED, fragmentTimecode=9998, fragmentNumber='91343852333182799103244234466928517092755016783', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=BUFFERING, fragmentTimecode=11997, fragmentNumber='91343852333182799108195994624070038382819825242', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=PERSISTED, fragmentTimecode=9998, fragmentNumber='91343852333182799103244234466928517092755016783', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=RECEIVED, fragmentTimecode=11997, fragmentNumber='91343852333182799108195994624070038382819825242', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=BUFFERING, fragmentTimecode=13997, fragmentNumber='91343852333182799113147754781211559531932668944', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=PERSISTED, fragmentTimecode=11997, fragmentNumber='91343852333182799108195994624070038382819825242', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=RECEIVED, fragmentTimecode=13997, fragmentNumber='91343852333182799113147754781211559531932668944', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=PERSISTED, fragmentTimecode=13997, fragmentNumber='91343852333182799113147754781211559531932668944', errorCode=null, errorId=null}
onComplete
onAckEvent AckEvent{ackEventType=BUFFERING, fragmentTimecode=0, fragmentNumber='91343852333182804030245590822742013834712528724', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=RECEIVED, fragmentTimecode=0, fragmentNumber='91343852333182804030245590822742013834712528724', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=BUFFERING, fragmentTimecode=1999, fragmentNumber='91343852333182804035197350979883534971093128738', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=PERSISTED, fragmentTimecode=0, fragmentNumber='91343852333182804030245590822742013834712528724', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=RECEIVED, fragmentTimecode=1999, fragmentNumber='91343852333182804035197350979883534971093128738', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=BUFFERING, fragmentTimecode=3999, fragmentNumber='91343852333182804040149111137025056309155360348', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=RECEIVED, fragmentTimecode=3999, fragmentNumber='91343852333182804040149111137025056309155360348', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=BUFFERING, fragmentTimecode=5998, fragmentNumber='91343852333182804045100871294166577434810966436', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=PERSISTED, fragmentTimecode=1999, fragmentNumber='91343852333182804035197350979883534971093128738', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=PERSISTED, fragmentTimecode=3999, fragmentNumber='91343852333182804040149111137025056309155360348', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=RECEIVED, fragmentTimecode=5998, fragmentNumber='91343852333182804045100871294166577434810966436', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=BUFFERING, fragmentTimecode=7998, fragmentNumber='91343852333182804050052631451308098753912888188', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=RECEIVED, fragmentTimecode=7998, fragmentNumber='91343852333182804050052631451308098753912888188', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=BUFFERING, fragmentTimecode=9998, fragmentNumber='91343852333182804055004391608449619876415542617', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=PERSISTED, fragmentTimecode=5998, fragmentNumber='91343852333182804045100871294166577434810966436', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=PERSISTED, fragmentTimecode=7998, fragmentNumber='91343852333182804050052631451308098753912888188', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=RECEIVED, fragmentTimecode=9998, fragmentNumber='91343852333182804055004391608449619876415542617', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=BUFFERING, fragmentTimecode=11997, fragmentNumber='91343852333182804059956151765591141020957855794', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=RECEIVED, fragmentTimecode=11997, fragmentNumber='91343852333182804059956151765591141020957855794', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=BUFFERING, fragmentTimecode=13997, fragmentNumber='91343852333182804064907911922732662143855030451', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=RECEIVED, fragmentTimecode=13997, fragmentNumber='91343852333182804064907911922732662143855030451', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=PERSISTED, fragmentTimecode=9998, fragmentNumber='91343852333182804055004391608449619876415542617', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=PERSISTED, fragmentTimecode=11997, fragmentNumber='91343852333182804059956151765591141020957855794', errorCode=null, errorId=null}
onAckEvent AckEvent{ackEventType=PERSISTED, fragmentTimecode=13997, fragmentNumber='91343852333182804064907911922732662143855030451', errorCode=null, errorId=null}
onComplete

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
