### ISSUE TITLE
[Question] Is the code of application somewhere published?

### ISSUE THREAD

**Issue by ievbu** [awsdocs/AWS-Kinesis-Video-Documentation#14]
I am looking at [Example: Identifying Objects in Video Streams Using Amazon SageMaker](https://github.com/awsdocs/AWS-Kinesis-Video-Documentation/blob/master/doc_source/examples-sagemaker.md). The given application can only send i-frames to SageMaker endpoint. However, I need to send every frame, so I want to edit the code of that application. Is this possible? Is somewhere the code of that application published?

**Comment by ghost** [comment]
> I am looking at [Example: Identifying Objects in Video Streams Using Amazon SageMaker](https://github.com/awsdocs/AWS-Kinesis-Video-Documentation/blob/master/doc_source/examples-sagemaker.md). The given application can only send i-frames to SageMaker endpoint. However, I need to send every frame, so I want to edit the code of that application. Is this possible? Is somewhere the code of that application published?

+1

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
