### ISSUE TITLE
Help With Controlling Access to Kinesis Video Streams Resources Using AWS IoT

### ISSUE THREAD

**Issue by istranic** [awsdocs/AWS-Kinesis-Video-Documentation#15]
I'm having trouble with the command on Windows:

_aws --profile default iam put-role-policy --role-name KVSCameraCertificateBasedIAMRole --policy-name KVSCameraIAMPolicy --policy-document file://iam-permission-document.json_

I get the error "An error occurred (MalformedPolicyDocument) when calling the PutRolePolicy operation: Syntax errors in policy."

I don't think it's caused by the command format, because the previous step work just fine:

_aws --profile default  iam create-role --role-name KVSCameraCertificateBasedIAMRole --assume-role-policy-document file://iam-policy-document.json > iam-role.json_

iam-permission-document.json looks like this:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "kinesisvideo:DescribeStream",
                "kinesisvideo:PutMedia",
                "kinesisvideo:TagStream",
                "kinesisvideo:GetDataEndpoint"
            ],
            "Resource": "arn:aws:kinesisvideo:*:*:stream/\${credentials-iot:ThingName}/*"
        }
    ]
}

When I try to create the permission in the AWS web interface, it says that the following line is a bad string:
"Resource": "arn:aws:kinesisvideo:*:*:stream/\${credentials-iot:ThingName}/*"

Is there a problem with the policy document itself?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
