### ISSUE TITLE
Using the C++ Producer SDK on Raspberry Pi:  'install-script': No such file or directory

### ISSUE THREAD

**Issue by enbochen** [awsdocs/AWS-Kinesis-Video-Documentation#18]
Related to this issue: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/456

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
