### ISSUE TITLE
[Question]: How to make a viewer connect to multiple channels created by different master [AWS Kinesis Video Strem]

### ISSUE THREAD

**Issue by VishalVerma97** [awsdocs/AWS-Kinesis-Video-Documentation#20]
Can u answer how to handle scenario where in a viewer needs to get connected to multiple channels to get video feeds from different master ?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
