### ISSUE TITLE
Documentation is incorrect: missing kinesis-video-native-build directory

### ISSUE THREAD

**Issue by gherlein** [awsdocs/AWS-Kinesis-Video-Documentation#26]
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/gs-send-data.html

"You can compile and install the GStreamer sample in the kinesis-video-native-build directory using the following commands:"

There is no kinesis-video-native-build directory, even after building it.

```
~/src/amazon-kinesis-video-streams-producer-sdk-cpp$ ls
build  CMake           dependency  LICENSE  open-source  samples  tst
certs  CMakeLists.txt  docs        NOTICE   README.md    src
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
