### ISSUE TITLE
Details on Raspberry Pi Tutorial

### ISSUE THREAD

**Issue by Shumakriss** [awsdocs/AWS-Kinesis-Video-Documentation#3]
Hi everyone, thanks for the work putting together KVS! I am working on a Raspberry Pi project and working through some issues getting the gstreamer sample app for the producer SDK to run. The contributors assisting with those tickets believe the issue with the encoder which I agree is a likely issue. However, I have not ruled out hardware and installed system packages as a potential reason for the issue. It would be very helpful to have more details about what was used to test the [Raspberry Pi tutorial](https://aws.amazon.com/kinesis/video-streams/raspberry-pi-tutorial/).

A few useful pieces of information:
- AWS KVS producer SDK CPP version (e.g. https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/tree/1.2.1)
- Raspberry Pi board version (e.g. Raspberry Pi 2 B v1.1)
- Picamera version (e.g v1.3)
- OS version (e.g. `cat /etc/os-release`)
- List of relevant packages (e.g. `dpkg -l`)
- System specs reported by OS (e.g `cat /proc/meminfo` or `cat/proc/cpuinfo`)
- Any notable hardware configuration (e.g. wired/wireless network, wifi device name, etc.)

I think this would help people make sure they have a supported setup before filing issues. It would especially help people like me who are just starting to learn about video compression formats and libraries to get to a working supported setup before experimenting and going deeper, if they even have to for their project.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
