### ISSUE TITLE
[Question] in creating role alias policy

### ISSUE THREAD

**Issue by cwrx777** [awsdocs/AWS-Kinesis-Video-Documentation#30]
Refer to step 4 in [Create an IAM Role to be Assumed by IoT](https://github.com/awsdocs/AWS-Kinesis-Video-Documentation/blob/master/doc_source/how-iot.md#how-iot-create-cert-keys).
What is the purpose of having `{
	 "Effect":"Allow",
	 "Action":[
	    "iot:Connect"
	 ],
	 "Resource":"$(jq --raw-output '.roleAliasArn' iot-role-alias.json)"
 },` in iot-policy-document?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
