### ISSUE TITLE
Sagemaker example - s3 access to Cloudformation template denied

### ISSUE THREAD

**Issue by dojciech1997** [awsdocs/AWS-Kinesis-Video-Documentation#31]
Hi, I have a problem with access to cfn templates. Error appears in every region. How can i solve that? I'm logged in as a root user. Shouldn't I have AdministratorAccess? I refer to public template: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/examples-sagemaker.html
Also, templates from other sources are available.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
