### ISSUE TITLE
Get a download url through getClip

### ISSUE THREAD

**Issue by diegocatalao** [awsdocs/AWS-Kinesis-Video-Documentation#33]
Hello.

Its possible generate a download URL from getClip function?
I would not like to receive a StreamingBody.

Tks.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
