### ISSUE TITLE
Links to PutMedia API documentation do not resolve

### ISSUE THREAD

**Issue by jrotenstein** [awsdocs/AWS-Kinesis-Video-Documentation#5]
The PI_dataplane_PutMedia.html page has links to API documentation such as:

- http://docs.aws.amazon.com/goto/boto3/kinesis-video-data-2017-09-30/PutMedia
- http://docs.aws.amazon.com/goto/aws-cli/kinesis-video-data-2017-09-30/PutMedia

However, these do not show documentation related to PutMedia.

**Comment by desaichirag06** [comment]
Hi,
I have been trying to integrate Kinesis Video Stream with Rekognition in an Android app and haven't been able to get best tutorials for the same.

I want to implement Facial Recognition and I am stuck at the step of PutMedia. In the demo as well as in documentation I only found details related to Java SDK and nothing related to Android SDK where I need to use Android app as Kinesis Producer and stream the video to the Rekognition service.

I have already referred the following links so far:
https://docs.aws.amazon.com/rekognition/latest/dg/recognize-faces-in-a-video-stream.html 
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/examples-putmedia.html 
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producer-sdk-android.html 
https://github.com/awslabs/aws-sdk-android-samples/tree/master/AmazonKinesisVideoDemoApp 
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producersdk-android-downloadcode.html 

Any help with the issue would be a great.

Thanks,
Chirag

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
